      tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "on-error-container": "#93000a",
              "on-primary-container": "#5b2500",
              "surface-container-low": "#f6f3f2",
              "surface-bright": "#fcf9f8",
              "surface-container": "#f0eded",
              "tertiary": "#934b00",
              "secondary-fixed-dim": "#ffb691",
              "surface-container-highest": "#e4e2e1",
              "on-tertiary-fixed-variant": "#703800",
              "error-container": "#ffdad6",
              "surface-dim": "#dcd9d9",
              "primary": "#9c4500",
              "on-secondary-fixed-variant": "#783100",
              "on-primary": "#ffffff",
              "secondary-container": "#fd771f",
              "secondary-fixed": "#ffdbcb",
              "primary-fixed": "#ffdbca",
              "on-tertiary": "#ffffff",
              "secondary": "#9e4300",
              "tertiary-fixed-dim": "#ffb782",
              "error": "#ba1a1a",
              "surface": "#fcf9f8",
              "on-primary-fixed": "#331200",
              "on-tertiary-container": "#552900",
              "surface-tint": "#9c4500",
              "primary-fixed-dim": "#ffb68e",
              "primary-container": "#ff7500",
              "inverse-primary": "#ffb68e",
              "outline-variant": "#e0c0b0",
              "inverse-surface": "#303030",
              "on-secondary-container": "#5c2400",
              "tertiary-container": "#e38739",
              "surface-variant": "#e4e2e1",
              "on-secondary": "#ffffff",
              "on-surface": "#1b1c1c",
              "inverse-on-surface": "#f3f0f0",
              "on-error": "#ffffff",
              "tertiary-fixed": "#ffdcc5",
              "on-surface-variant": "#594236",
              "on-tertiary-fixed": "#301400",
              "outline": "#8c7163",
              "surface-container-high": "#eae7e7",
              "on-primary-fixed-variant": "#773300",
              "on-secondary-fixed": "#341100",
              "background": "#fcf9f8",
              "on-background": "#1b1c1c",
              "surface-container-lowest": "#ffffff"
            },
            fontFamily: {
              "headline": ["Inter"],
              "body": ["Inter"],
              "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
          },
        },
      }
